# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdate', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('offeredsalary', models.FloatField()),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
    ]
