# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-13 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='conductinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='conductinfo_ptr',
        ),
        migrations.DeleteModel(
            name='ConductInfo',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
